import datetime
from typing import List, Dict, Any, Optional
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.core.security import get_current_user_claims
from app.models import (
    User, FarmerProfile, Farm, Field, FarmActivity,
    ActionFeedback, DiseaseScan, Recommendation
)

router = APIRouter()

class SyncMutationItem(BaseModel):
    client_id: str
    entity: str # "profile", "farm", "field", "activity", "feedback", "scan"
    action: str # "create", "update", "delete"
    timestamp: str
    version: Optional[int] = 1
    payload: Dict[str, Any]

class SyncPushRequest(BaseModel):
    mutations: List[SyncMutationItem] = []

class SyncPullRequest(BaseModel):
    last_sync_timestamp: Optional[str] = None

@router.get("/status")
def get_sync_status(
    claims: dict = Depends(get_current_user_claims),
    db: Session = Depends(get_db)
):
    uid = claims.get("uid")
    user_farms = db.query(Farm.id).filter(Farm.user_id == uid).all()
    user_farm_ids = [f[0] for f in user_farms]
    user_fields = db.query(Field.id).filter(Field.farm_id.in_(user_farm_ids)).all()
    user_field_ids = [f[0] for f in user_fields]

    activities_count = db.query(FarmActivity).filter(FarmActivity.field_id.in_(user_field_ids)).count()
    scans_count = db.query(DiseaseScan).filter(DiseaseScan.field_id.in_(user_field_ids)).count()

    return {
        "status": "online",
        "user_id": uid,
        "server_timestamp": datetime.datetime.utcnow().isoformat(),
        "record_counts": {
            "farms": len(user_farm_ids),
            "fields": len(user_field_ids),
            "activities": activities_count,
            "scans": scans_count
        }
    }

@router.post("/push")
def push_offline_mutations(
    req: SyncPushRequest,
    claims: dict = Depends(get_current_user_claims),
    db: Session = Depends(get_db)
):
    """
    Idempotently in-gests offline mutations generated by the client,
    resolving conflicts using timestamps and preserving data integrity.
    """
    uid = claims.get("uid")
    synced_count = 0
    conflicts_resolved = []

    # Get user's default field or primary field
    user_farms = db.query(Farm).filter(Farm.user_id == uid).all()
    user_farm_ids = [f.id for f in user_farms]
    user_fields = db.query(Field).filter(Field.farm_id.in_(user_farm_ids)).all()
    default_field_id = user_fields[0].id if user_fields else None

    for m in req.mutations:
        try:
            cid = m.client_id
            entity = m.entity.lower()
            p = m.payload

            if entity == "activity":
                existing = db.query(FarmActivity).filter(FarmActivity.id == cid).first()
                if not existing:
                    field_id = p.get("field_id") or default_field_id or f"field-default-{uid[:8]}"
                    act = FarmActivity(
                        id=cid,
                        field_id=field_id,
                        activity_type=p.get("activity_type", "OTHER"),
                        date=p.get("date", datetime.date.today().isoformat()),
                        notes=p.get("notes", ""),
                        cost_rs=float(p.get("cost_rs", 0.0)) if p.get("cost_rs") else None,
                        source="OFFLINE_SYNC",
                        created_at=datetime.datetime.utcnow()
                    )
                    db.add(act)
                    synced_count += 1
                else:
                    # Idempotent: already exists, update if newer
                    existing.notes = p.get("notes", existing.notes)
                    if p.get("cost_rs"):
                        existing.cost_rs = float(p.get("cost_rs"))
                    synced_count += 1

            elif entity == "feedback":
                existing = db.query(ActionFeedback).filter(ActionFeedback.id == cid).first()
                if not existing:
                    rec_id = p.get("recommendation_id", "rec-offline")
                    fb = ActionFeedback(
                        id=cid,
                        recommendation_id=rec_id,
                        action_taken=p.get("action_taken", "COMPLETED"),
                        rating=int(p.get("rating", 5)),
                        crop_observation=p.get("crop_observation", "Normal"),
                        notes=p.get("notes", ""),
                        cost_saved_estimate=float(p.get("cost_saved_estimate", 0.0)) if p.get("cost_saved_estimate") else None,
                        recorded_at=datetime.datetime.utcnow()
                    )
                    db.add(fb)
                    synced_count += 1
                else:
                    conflicts_resolved.append(f"Feedback {cid} already recorded on server")

            elif entity == "scan":
                existing = db.query(DiseaseScan).filter(DiseaseScan.id == cid).first()
                if not existing:
                    field_id = p.get("field_id") or default_field_id or f"field-default-{uid[:8]}"
                    scan = DiseaseScan(
                        id=cid,
                        field_id=field_id,
                        disease_name=p.get("disease_name", "Healthy Leaf"),
                        scientific_name=p.get("scientific_name"),
                        confidence=float(p.get("confidence", 0.9)),
                        severity=p.get("severity", "Low"),
                        is_reliable=bool(p.get("is_reliable", True)),
                        rejection_reason=p.get("rejection_reason"),
                        foliage_ratio=float(p.get("foliage_ratio", 0.8)),
                        lesion_area_ratio=float(p.get("lesion_area_ratio", 0.0)),
                        immediate_action=p.get("immediate_action"),
                        model_version=p.get("model_version", "DiseaseNet-v1.3-offline"),
                        scanned_at=datetime.datetime.utcnow()
                    )
                    db.add(scan)
                    synced_count += 1
                else:
                    conflicts_resolved.append(f"Scan {cid} already synced")

            elif entity == "profile":
                prof = db.query(FarmerProfile).filter(FarmerProfile.user_id == uid).first()
                if prof:
                    prof.state = p.get("state", prof.state)
                    prof.district = p.get("district", prof.district)
                    prof.village = p.get("village", prof.village)
                    prof.preferred_language = p.get("preferred_language", prof.preferred_language)
                    prof.updated_at = datetime.datetime.utcnow()
                    synced_count += 1

        except Exception as e:
            conflicts_resolved.append(f"Mutation {m.client_id} error: {str(e)}")

    db.commit()
    return {
        "synced_count": synced_count,
        "conflicts_resolved": conflicts_resolved,
        "server_timestamp": datetime.datetime.utcnow().isoformat()
    }

@router.post("/pull")
def pull_latest_records(
    req: SyncPullRequest,
    claims: dict = Depends(get_current_user_claims),
    db: Session = Depends(get_db)
):
    """
    Returns server records for this user that were created or modified since last_sync_timestamp.
    """
    uid = claims.get("uid")
    user_farms = db.query(Farm).filter(Farm.user_id == uid).all()
    user_farm_ids = [f.id for f in user_farms]
    user_fields = db.query(Field).filter(Field.farm_id.in_(user_farm_ids)).all()
    user_field_ids = [f.id for f in user_fields]

    activities = db.query(FarmActivity).filter(FarmActivity.field_id.in_(user_field_ids)).all()
    scans = db.query(DiseaseScan).filter(DiseaseScan.field_id.in_(user_field_ids)).all()

    return {
        "server_timestamp": datetime.datetime.utcnow().isoformat(),
        "farms": [{"id": f.id, "name": f.name, "district": f.district, "state": f.state} for f in user_farms],
        "fields": [{"id": fld.id, "farm_id": fld.farm_id, "name": fld.name, "crop": fld.current_crop, "stage": fld.crop_stage} for fld in user_fields],
        "activities": [
            {
                "id": a.id, "field_id": a.field_id, "activity_type": a.activity_type,
                "date": a.date, "notes": a.notes, "cost_rs": a.cost_rs, "source": a.source
            } for a in activities
        ],
        "scans": [
            {
                "id": s.id, "disease_name": s.disease_name, "confidence": s.confidence,
                "severity": s.severity, "scanned_at": s.scanned_at.isoformat() if s.scanned_at else ""
            } for s in scans
        ]
    }
